---
name: oss-jenkins-3a71100ab3921faedff0
director_uuid: c8866a05-dd2a-4211-9fbd-285f3fb02367
releases:
- name: oss-jenkins
  version: 0.0.8
- name: docker
  version: '23'
stemcells:
- alias: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  os: ubuntu-trusty
  version: '3262.12'
instance_groups:
- name: docker-bosh-jenkins
  azs:
  - us-west-2a
  instances: 1
  lifecycle: service
  jobs:
  - name: containers
    release: docker
    consumes: {}
    provides: {}
  - name: docker
    release: docker
    consumes: {}
    provides: {}
  - name: docker-bosh-jenkins
    release: oss-jenkins
    consumes: {}
    provides: {}
  vm_type: c4.large
  stemcell: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  properties:
    containers:
    - bind_ports:
      - 8080:8080
      - 50000:50000
      env_vars:
      - JAVA_OPTS=-Xmx2048m
      image: jenkins
      name: jenkins
  env: {}
  update:
    max_in_flight: 1
  networks:
  - name: public
    default:
    - dns
    - gateway
  #  static_ips:
  #  - 10.0.16.13
  migrated_from:
  - name: docker-bosh-jenkins-partition-d6b9d61d1ac1a01f21ba
    az: us-west-2a
  persistent_disk_type: '5120'
update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: true
